#disable_all_formatting = false
#unstable_features = true
edition = "2018"

use_small_heuristics = "Max"
fn_args_layout = "Tall"
hard_tabs = false
force_explicit_abi = true
max_width = 80
merge_derives = true
newline_style = "Unix"
remove_nested_parens = true
reorder_imports = true
reorder_modules = false
tab_spaces = 4
use_field_init_shorthand = true
use_try_shorthand = true
array_width = 80
attr_fn_like_width = 80
chain_width = 80
fn_call_width = 80
match_arm_leading_pipes = "Never"
single_line_if_else_max_width = 80
struct_lit_width = 80
struct_variant_width = 80

#indent_style = "Block"
#binop_separator = "Front"
#combine_control_expr = true
#comment_width = 80
#condense_wildcard_suffixes = true
#control_brace_style = "AlwaysSameLine"
#error_on_line_overflow = false
#error_on_unformatted = false
#brace_style = "SameLineWhere"
#empty_item_single_line = true
#fn_single_line = false
#where_single_line = false
#format_strings = true
#format_macro_matchers = false
#format_macro_bodies = true
#imports_indent = "Block"
#imports_layout = "HorizontalVertical"
#imports_granularity = "Crate"
#match_block_trailing_comma = true
#force_multiline_blocks = false
#normalize_comments = false
#reorder_impl_items = false
#report_todo = "Never"
#report_fixme = "Never"
#skip_children = false
#space_after_colon = true
#space_before_colon = false
#struct_field_align_threshold = 0
#spaces_around_ranges = true
#struct_lit_single_line = true
#trailing_comma = "Vertical"
#trailing_semicolon = true
#type_punctuation_density = "Wide"
#wrap_comments = true
#match_arm_blocks = true
#blank_lines_upper_bound = 1
#blank_lines_lower_bound = 0
#hide_parse_errors = false
