[package]
name = "lambda"
version = "0.1.0"
authors = ["brunoczim <brunoczim@gmail.com>"]
edition = "2018"
workspace = "../"

[dependencies]
indexmap = "1.7.0"
pinguim-language = {git = "https://github.com/petcomputacaoufrgs/pinguim-language"}